version = 0.1

[default.deploy.parameters]
stack_name = "nws-weather-alerts"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "nws-weather-alerts"
image_repositories = []
